name = "gleam_otp"
version = "1.0.0-rc2"
licences = ["Apache-2.0"]
description = "Fault tolerant multicore Gleam programs with OTP"

gleam = ">= 1.7.0"

repository = { type = "github", user = "gleam-lang", repo = "otp" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.59.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0-rc1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
