name = "gleam_otp"
version = "1.1.0"
licences = ["Apache-2.0"]
description = "Fault tolerant multi-core programs with OTP, the BEAM actor framework."

gleam = ">= 1.11.0"

repository = { type = "github", user = "gleam-lang", repo = "otp" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
